var DOCUMENTATION_OPTIONS = {
    URL_ROOT: '',
    VERSION: '1.11.12.dev20180320010640',
    LANGUAGE: 'en',
    COLLAPSE_INDEX: false,
    FILE_SUFFIX: '.html',
    HAS_SOURCE: true,
    SOURCELINK_SUFFIX: '.txt'
};